package constants

const (
	VIRTUAL_ACCOUNT = "VIRTUAL_ACCOUNT"
	BCA_VA          = "VIRTUAL_ACCOUNT_BCA"
	Mandiri_VA      = "VIRTUAL_ACCOUNT_BANK_MANDIRI"
	BSI_VA          = "VIRTUAL_ACCOUNT_BANK_SYARIAH_MANDIRI"
	BRI_VA          = "VIRTUAL_ACCOUNT_BRI"
	BNI_VA          = "VIRTUAL_ACCOUNT_BNI"
	DOKU_VA         = "VIRTUAL_ACCOUNT_DOKU"
	PERMATA_VA      = "VIRTUAL_ACCOUNT_BANK_PERMATA"
	CIMB_VA         = "VIRTUAL_ACCOUNT_BANK_CIMB"
	DANAMON_VA      = "VIRTUAL_ACCOUNT_BANK_DANAMON"
	BTN_VA          = "VIRTUAL_ACCOUNT_BTN"
	BNC_VA          = "VIRTUAL_ACCOUNT_BNC"

	CREDIT_CARD = "CREDIT_CARD"

	ALFA_GROUP = "ONLINE_TO_OFFLINE_ALFA"
	INDOMARET  = "ONLINE_TO_OFFLINE_INDOMARET"

	QRIS = "QRIS"

	OVO         = "EMONEY_OVO"
	SHOPEEPAY   = "EMONEY_SHOPEE_PAY"
	DOKU_WALLET = "EMONEY_DOKU"
	LINKAJA     = "EMONEY_LINKAJA"
	DANA        = "EMONEY_DANA"

	PAYLATER_AKULAKU  = "PEER_TO_PEER_AKULAKU"
	PAYLATER_KREDIVO  = "PEER_TO_PEER_KREDIVO"
	PAYLATER_INDODANA = "PEER_TO_PEER_INDODANA"

	DIRECT_DEBIT_BRI = "DIRECT_DEBIT_BRI"

	JENIUS_PAY = "JENIUS_PAY"

	KKI = "KARTU_KREDIT_INDONESIA"
)

var DokuPaymentMethodMap = map[string]string{
	VIRTUAL_ACCOUNT:   VIRTUAL_ACCOUNT,
	BCA_VA:            VIRTUAL_ACCOUNT,
	Mandiri_VA:        VIRTUAL_ACCOUNT,
	BSI_VA:            VIRTUAL_ACCOUNT,
	BRI_VA:            VIRTUAL_ACCOUNT,
	BNI_VA:            VIRTUAL_ACCOUNT,
	DOKU_VA:           VIRTUAL_ACCOUNT,
	PERMATA_VA:        VIRTUAL_ACCOUNT,
	CIMB_VA:           VIRTUAL_ACCOUNT,
	DANAMON_VA:        VIRTUAL_ACCOUNT,
	BTN_VA:            VIRTUAL_ACCOUNT,
	BNC_VA:            VIRTUAL_ACCOUNT,
	CREDIT_CARD:       CREDIT_CARD,
	ALFA_GROUP:        ALFA_GROUP,
	INDOMARET:         INDOMARET,
	QRIS:              QRIS,
	OVO:               OVO,
	SHOPEEPAY:         SHOPEEPAY,
	DOKU_WALLET:       DOKU_WALLET,
	LINKAJA:           LINKAJA,
	DANA:              DANA,
	PAYLATER_AKULAKU:  PAYLATER_AKULAKU,
	PAYLATER_KREDIVO:  PAYLATER_KREDIVO,
	PAYLATER_INDODANA: PAYLATER_INDODANA,
	DIRECT_DEBIT_BRI:  DIRECT_DEBIT_BRI,
	JENIUS_PAY:        JENIUS_PAY,
	KKI:               KKI,
}
